### ISSUE TITLE
Edit vertex feature

### ISSUE THREAD

**Issue by chhipanikhil9** [thud/gravy#2]
You can add the **edit vertex** feature also so we can also edit vertex and give it the name **` null `** because it is easy to use for beginners.

**Comment by thud** [comment]
Thanks for your patience but unless this receives more support from others, I think that it probably isn't worth the effort. It would require several non-trivial changes and I'm not so familiar with the codebase anymore. If you feel strongly about it, then feel free to implement it yourself.
For now I'm closing this issue but feel free to reopen if you have changes.
